import type { Question } from '@/lib/assessment/types'

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    text: 'How are you feeling right now, in this moment?',
    subtext: "There's no right answer. Just pick what's closest.",
    options: [
      { label: 'Heavy and tired',                   microcopy: 'That kind of exhaustion runs deeper than sleep.' },
      { label: 'Anxious and spiralling',             microcopy: "When your mind won't stop, it takes everything just to stay present." },
      { label: "Numb — like I can't feel much",      microcopy: "Numbness is its own kind of weight." },
      { label: "Sad, but I'm managing",              microcopy: 'Managing takes more out of you than it looks.' },
      { label: 'Okay on the surface, hollow inside', microcopy: 'That gap between how you look and how you feel is exhausting to maintain.' },
      { label: "Honestly, I don't know",             microcopy: "Not knowing is a feeling too. You're in the right place." },
    ],
  },
  {
    id: 'q2',
    text: 'How long have you been feeling this way?',
    subtext: 'Take your best guess — there is no judgment here.',
    options: [
      { label: 'A few days',                               microcopy: 'Even a few days of this can feel like much longer.' },
      { label: 'A few weeks',                              microcopy: "Weeks of this kind of weight is a long time to carry it quietly." },
      { label: 'A few months',                             microcopy: "Months of this — you've been holding a lot." },
      { label: 'On and off for years',                     microcopy: "When it keeps coming back, it's telling you something needs tending." },
      { label: "I can't remember feeling okay",            microcopy: "That's a long time to have carried this alone." },
      { label: 'It just started, and it hit hard',         microcopy: 'The sudden ones can feel the most disorienting.' },
    ],
  },
  {
    id: 'q3',
    text: 'How has your sleep been lately?',
    subtext: 'Our bodies often carry what our minds are still processing.',
    options: [
      { label: "Can't sleep — too many thoughts",      microcopy: '3am thoughts are their own kind of lonely.' },
      { label: 'Sleeping too much, to escape',         microcopy: 'Sleep as refuge is one of the quieter signs something is heavy.' },
      { label: 'Restless — I wake up exhausted',       microcopy: 'Your nervous system is still working through something.' },
      { label: "Sleep is fine, but nothing else is",   microcopy: 'Sometimes the body holds on even when everything else is falling apart.' },
      { label: 'My whole routine has collapsed',       microcopy: "When structure goes, everything can start to unravel." },
      { label: 'Sleep is okay — this is more my mind', microcopy: "Your mind knows what it needs. Let's listen to it." },
    ],
  },
  {
    id: 'q4',
    text: 'How connected do you feel to the people in your life?',
    subtext: 'Be honest — no one is listening but this.',
    options: [
      { label: 'Very alone, even around people',           microcopy: 'That specific kind of lonely — in a crowd — is one of the heaviest.' },
      { label: "I've been pulling away lately",            microcopy: "Pulling away is often how we protect ourselves when we don't have words yet." },
      { label: "I have people, but I can't open up",       microcopy: "Having people who don't quite reach you is its own quiet ache." },
      { label: 'One or two people know a little',          microcopy: 'That takes more courage than it sounds.' },
      { label: 'I have support, but I need more',          microcopy: 'Knowing what you need is already a step.' },
      { label: "I feel okay with my relationships",        microcopy: "Then something else is asking for attention. We'll find it." },
    ],
  },
  {
    id: 'q5',
    text: "What's weighing on you most these days?",
    subtext: "Choose what feels closest. There's no wrong answer.",
    options: [
      { label: 'Loneliness',                  microcopy: 'That kind of quiet is real — even in a crowd.' },
      { label: 'Relationships & heartbreak',   microcopy: 'That kind of pain has a way of quietly taking up every room in your head.' },
      { label: 'Family pressure',              microcopy: "That weight is real. And it's exhausting to carry quietly." },
      { label: 'Work & future stress',         microcopy: "There's so much noise when you're trying to figure out your own path." },
      { label: "I can't put a name to it",     microcopy: "Sometimes there aren't words. That's why we're here." },
      { label: 'All of the above',             microcopy: "When it's everything at once — that's one of the heaviest feelings there is. You're in the right place." },
    ],
  },
  {
    id: 'q6',
    text: 'Where does this heaviness tend to show up for you?',
    subtext: "Sometimes it's easier to notice the body than the feelings.",
    options: [
      { label: "I can't concentrate on anything",          microcopy: 'A scattered mind is often a tired heart in disguise.' },
      { label: "I've stopped enjoying things I used to",   microcopy: "When the small joys quiet down, it's worth paying attention." },
      { label: 'I feel it physically — chest, fatigue',    microcopy: "Your body is carrying something. It's okay to put it down." },
      { label: "I've been avoiding people and places",     microcopy: 'Avoidance takes real energy. You have been working hard just to get through.' },
      { label: "My mood swings — I don't feel like me",    microcopy: "Not feeling like yourself is disorienting. You deserve to find your footing again." },
      { label: "It's everywhere — it's the background now",microcopy: "When it becomes the background, it's easy to forget it wasn't always like this." },
    ],
  },
  {
    id: 'q7',
    text: 'Have you talked to anyone about what you are going through?',
    subtext: 'No judgment either way.',
    options: [
      { label: "No — I don't want to be a burden",    microcopy: "The people who love you would want to know. But we understand." },
      { label: "I've tried, but it didn't help",       microcopy: "Being heard the wrong way can feel worse than not being heard at all." },
      { label: "A little — but not the full picture",  microcopy: 'Sharing in pieces is still sharing. That takes something.' },
      { label: 'Yes, to friends or family',            microcopy: 'That connection matters. Sometimes we still need more.' },
      { label: "I've seen a therapist before",         microcopy: "You know what real support can feel like. You deserve to find it again." },
      { label: 'I prefer to work through things alone',microcopy: "Self-reliance has its place. And so does a space that's just for you." },
    ],
  },
  {
    id: 'q8',
    text: 'When things get really hard, what do you usually do?',
    subtext: 'Honest answers help us understand you better.',
    options: [
      { label: "I go quiet and wait for it to pass",       microcopy: 'Riding it out alone takes a kind of endurance most people never see.' },
      { label: 'I throw myself into work or distractions', microcopy: "Staying busy can be a way of surviving. You don't have to do it alone." },
      { label: 'I reach out to someone close',             microcopy: 'That impulse toward connection is worth nurturing.' },
      { label: 'I journal, exercise, or find an outlet',   microcopy: "You have built something to hold onto. Let's see what else might help." },
      { label: "I shut down — I can't really do anything", microcopy: "When everything feels too heavy to move — that's exactly what we're here for." },
      { label: "It depends. I don't have a pattern",       microcopy: "That inconsistency is something we can work with." },
    ],
  },
  {
    id: 'q9',
    text: 'What are you hoping for — even if it feels far away?',
    subtext: 'Even a vague answer is enough.',
    options: [
      { label: "To feel like myself again",                  microcopy: "That version of you is still there. Let's help you find your way back." },
      { label: "To stop feeling so alone in this",           microcopy: "You won't, once you have the right space." },
      { label: "To actually process what happened",          microcopy: "That processing is possible. You don't have to carry it unresolved." },
      { label: "To have better relationships",               microcopy: "The patterns that hurt us can change. You have already taken the first step." },
      { label: "To feel calmer — to quiet the noise",        microcopy: "Calm isn't permanent silence. It's knowing you can come back to yourself." },
      { label: "I just needed somewhere to start",           microcopy: "Starting is the whole thing. You're already here." },
    ],
  },
  {
    id: 'q10',
    text: 'What feels right for you, right now?',
    subtext: 'This helps us point you toward the best next step.',
    options: [
      { label: "Talk to someone who's been through it",  microcopy: "That's what an Ally is — no therapy, just a warm human who gets it." },
      { label: "Talk to Nila — no waiting, no booking",  microcopy: "Nila is always here. No appointments, no judgment." },
      { label: "Read and explore at my own pace",        microcopy: "Resources are here whenever you're ready." },
      { label: "Try a gentle in-person gathering",       microcopy: "Sometimes being around people who get it — without explaining yourself — is everything." },
      { label: "Just see what's here first",             microcopy: "Take your time. We'll be here." },
      { label: "Show me what you recommend",             microcopy: "Based on everything you've shared, we'll find the right fit." },
    ],
  },
]
